FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Person-API/Person-API.csproj", "Person-API/"]
RUN dotnet restore "Person-API/Person-API.csproj"
COPY . .
WORKDIR "/src/Person-API"
RUN dotnet build "Person-API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Person-API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Person-API.dll"]